print("Two vectors of different lengths:")
v1 =  c(1,3,4,5)
v2 =  c(10,11,12,13,14,15)
print(v1)
print(v2)
A = array(c(v1,v2),dim = c(3,3,2))
print("New array:")
print(A)
print("The second row of the second matrix of the array:")
print(A[2,,2])
print("The element in the 3rd row and 3rd column of the 1st matrix:")
print(A[3,3,1])