numeric_vector <- c(11,32,45,78)
charecter_vector <- c("red","yellow","blue","green")
logical_vector <- c(T,F,T,F)
cat("numeric vector:\n")
print(numeric_vector)
cat("charecter vector:\n")
print(charecter_vector)
cat("logical vector:\n")
print(logical_vector)